"""Model registry helper for JetSeg.

This module provides a small registry API used by `HumanSeg` to resolve
friendly model names (e.g. "human_seg_tiny") to packaged artifacts.

Behavior:
- If `model_registry.json` exists in the package it is loaded.
- Otherwise the registry is generated by scanning `jetseg/model_store/`.

API:
- `load_registry()` -> dict
- `get_model_path(task, model_name, variant=None)` -> Path | None
- `get_default_variant(task, model_name)` -> str | None
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, Optional

_PKG_DIR = Path(__file__).parent
_REG_JSON = _PKG_DIR / "model_registry.json"
_MODEL_STORE = _PKG_DIR / "model_store"
_CACHE: Optional[Dict[str, Any]] = None


def _scan_model_store() -> Dict[str, Any]:
    reg: Dict[str, Any] = {}
    if not _MODEL_STORE.exists():
        return reg

    for task_dir in sorted(_MODEL_STORE.iterdir()):
        if not task_dir.is_dir():
            continue
        task = task_dir.name
        models: Dict[str, Any] = {}
        default_model: Optional[str] = None

        for model_dir in sorted(task_dir.iterdir()):
            if not model_dir.is_dir():
                continue
            model_name = model_dir.name
            if default_model is None:
                default_model = model_name

            variants: Dict[str, str] = {}
            for f in sorted(model_dir.iterdir()):
                if not f.is_file():
                    continue
                lname = f.name.lower()
                if f.suffix.lower() == ".onnx":
                    if "_fp32" in lname:
                        variants["fp32"] = str(f.relative_to(_PKG_DIR))
                    elif "_fp16" in lname:
                        variants["fp16"] = str(f.relative_to(_PKG_DIR))
                    elif "_int8" in lname:
                        variants["int8"] = str(f.relative_to(_PKG_DIR))
                    else:
                        # generic onnx
                        variants.setdefault("onnx", str(f.relative_to(_PKG_DIR)))
                elif f.suffix.lower() in (".pt", ".pth"):
                    variants.setdefault("pth", str(f.relative_to(_PKG_DIR)))

            if variants:
                # pick a sensible preferred variant
                preferred = None
                for key in ("fp32", "fp16", "onnx", "pth"):
                    if key in variants:
                        preferred = key
                        break
                models[model_name] = {"variants": variants, "preferred_variant": preferred}

        if models:
            reg[task] = {"default": default_model, "models": models}

    return reg


def load_registry() -> Dict[str, Any]:
    """Load the model registry.

    Returns a dict mapping task -> {"default": model_name, "models": { ... }}.
    """
    global _CACHE
    if _CACHE is not None:
        return _CACHE

    if _REG_JSON.exists():
        try:
            data = json.loads(_REG_JSON.read_text(encoding="utf8"))
            _CACHE = data
            return _CACHE
        except Exception:
            # fall back to scanning
            pass

    _CACHE = _scan_model_store()
    return _CACHE


def get_default_variant(task: str, model_name: str) -> Optional[str]:
    reg = load_registry()
    try:
        m = reg.get(task, {}).get("models", {}).get(model_name)
        if not m:
            return None
        return m.get("preferred_variant")
    except Exception:
        return None


def get_model_path(task: str, model_name: str, variant: Optional[str] = None) -> Optional[Path]:
    """Return the filesystem Path to the requested model artifact (or None).

    If `variant` is None the model's preferred variant is used.
    """
    reg = load_registry()
    task_entry = reg.get(task, {})
    models = task_entry.get("models", {})
    model_entry = models.get(model_name)
    if not model_entry:
        return None

    variants = model_entry.get("variants", {})
    if variant is None:
        variant = model_entry.get("preferred_variant")

    vpath = None
    if variant and variant in variants:
        vpath = variants[variant]
    else:
        # fallback to any variant path
        for _p in variants.values():
            vpath = _p
            break

    if vpath is None:
        return None

    p = Path(vpath)
    if not p.is_absolute():
        p = _PKG_DIR / p
    return p


__all__ = ["load_registry", "get_model_path", "get_default_variant"]
